### ISSUE TITLE
Fix Check Migration on Actions

### ISSUE THREAD

**Issue by jfcodiaz** [jfcodiaz/my-vocabulary-api#34]
The migrations was removed to prevent confict with the db tests

```yml
      - name: Run Migrations
        working-directory: ./code
        run: php artisan migrate

      - name: Rollback Migrations
        working-directory: ./code
        run: php artisan migrate:rollback

      - name: Re-run Migrations
        working-directory: ./code
        run: php artisan migrate
```
